// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package main

import "strconv"

const _TokenType_name = "VarTokenAssignTokenStartFuncCallTokenEndFuncCallTokenLineEndTokenMultOpTokenDivideOpTokenSubOpTokenAddOpTokenModOpTokenPipeTokenEndLineTokenStartArrayLiteralTokenEndArrayLiteralTokenByteLiteralTokenIntLiteralTokenFloatLiteralTokenHexLiteralTokenStartFunctionDefinitionEndFunctionDefinitionEqualityCompareToken"

var _TokenType_index = [...]uint16{0, 8, 19, 37, 53, 65, 76, 89, 99, 109, 119, 128, 140, 162, 182, 198, 213, 230, 245, 268, 289, 309}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
