// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package main

import "strconv"

const _TokenType_name = "VarTokenAssignTokenStartVarGroupEndVarGroupLineEndTokenMultOpTokenDivideOpTokenSubOpTokenAddOpTokenModOpTokenPipeTokenEndLineTokenStartArrayLiteralTokenEndArrayLiteralTokenByteLiteralTokenIntLiteralTokenFloatLiteralTokenHexLiteralTokenStartFunctionDefinitionEndFunctionDefinitionEqualityCompareToken"

var _TokenType_index = [...]uint16{0, 8, 19, 32, 43, 55, 66, 79, 89, 99, 109, 118, 130, 152, 172, 188, 203, 220, 235, 258, 279, 299}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
